personal_tools/blueprints/coins.py
from os import getenv
from personal_tools import mongodb
from personal_tools.utils import filters
from personal_tools.utils.formatting import return_name_of_coin
from flask import Blueprint, render_template


coins = Blueprint("coins", __name__, url_prefix="/coins")
coins.add_app_template_filter(filters.format_coin)
coins.add_app_template_filter(filters.add_underscore)
coins.add_app_template_filter(filters.remove_special_characters)

version = getenv("VERSION", "")
environment = getenv("FLASK_ENV", "")


def get_coin(coin, limit=200):
    dates = [
        item["datetime"].strftime("%m/%d/%Y %H:%M")
        for item in mongodb.db.coins.find({"name": coin}, {"datetime": 1})
        .sort("_id", -1)
        .limit(limit)
    ]

    values = [
        item["value"]
        for item in mongodb.db.coins.find({"name": coin}, {"value": 1})
        .sort("_id", -1)
        .limit(limit)
    ]

    data = {
        "name": coin,
        "dates": dates,
        "values": values,
    }

    return data


@coins.get("/")
def index():
    coins = mongodb.db.coins.find().sort("_id", -1).limit(12)
    coins_bc_purchase = (
        mongodb.db.coins.find({"name": "Dólar BC - Compra"})
        .sort("_id", -1)
        .limit(1)[0]
    )
    coins_bc_sale = (
        mongodb.db.coins.find({"name": "Dólar BC - Venda"})
        .sort("_id", -1)
        .limit(1)[0]
    )
    footer = f"Updated at: {coins[0]['datetime'].strftime('%d/%m/%Y - %H:%M')}"
    return render_template(
        "coins/index.html",
        purchase=coins_bc_purchase,
        sale=coins_bc_sale,
        data=coins,
        footer=footer,
    )


@coins.get("/<coin_name>")
def return_coin(coin_name):
    coin_name = return_name_of_coin(coin_name)
    data = {
        "coins": get_coin(coin_name),
        "version": version,
        "environment": environment,
    }
    return render_template("coins/chart.html", **data)

personal_tools/templates/coins/chart.html
{% extends 'layout.html' %}
{% block title %}{{ super() }}| Coins{% endblock %}}
{% block page %} Index {% endblock %}}
{% block content %}
    <div class="content mt-5">
        <div class="chart-container">
            <canvas id="chart"></canvas>
        </div>
        <div class="has-text-centered">
            <a href="{{ url_for('coins.index') }}" class="button is-link is-outlined">Back</a>
        </div>
        <script type="text/javascript" src="{{ url_for('static', filename='js/Chart.js') }}"></script>
        <script>
            var data = {
                labels: [{% for date in coins["dates"] %} "{{ date }}", {% endfor %}],
                datasets: [{
                    label: "{{ coins['name'] }}",
                    borderColor: "teal",
                    borderWidth: 2,
                    data: [{% for value in coins["values"] %} {{ value }}, {% endfor %}],
                    fill: true,
                }]
            };
            var options = {
                maintainAspectRatio: false,
                scales: {
                    yAxes: [{
                        ticks: {
                            callback: function(value, index, values) {
                                return (
                                    Math.round(value * 100) / 100).toLocaleString('pt-br',{style: 'currency', currency: 'BRL'}
                                );
                            }
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            maxTicksLimit: 10,
                            display: true,
                        },
                        gridLines: {
                            display: false
                        }
                    }],
                },
                tooltips: {
                    callbacks: {
                        label: function (tooltipItem, data) {
                            let label = data.datasets[tooltipItem.datasetIndex].label;
                            let value = data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];
                            return label + ": " + value.toLocaleString('pt-br',{style: 'currency', currency: 'BRL'});
                        }
                    }
                }
            };
            new Chart(document.getElementById("chart"), {
                type: 'line',
                data: data,
                options: options,
            });
        </script>
    </div>
{% endblock %}

personal_tools/templates/coins/index.html
{% extends 'layout.html' %}
{% block title %}{{ super() }}| Coins{% endblock %}}
{% block page %} Index {% endblock %}}
{% block content %}
<div class="content mt-5">
  <div class="columns is-mobile is-multiline">
    {% for coin in data | sort(attribute='order') %}
      <div class="column is-4-desktop is-6-tablet is-12-mobile">
        <a href="{{ url_for('coins.index') }}{{ coin.name | lower | remove_special_characters | add_underscore }}">
          <div class="box">
            <article class="media">
              <div class="media-left">
                <figure class="image is-64x64">
                  <img {% if coin.name == "Ouro"  %} style="margin-top: 15px;" {% endif %}
                      src="{{ url_for('static', filename="/images") }}/{{coin.image}}" alt="{{ coin.image }}">
                </figure>
              </div>
              <div class="media-content">
                <div class="content">
                  <div style="margin-top: 6px;">
                    {% if coin.name == "Dólar"  %}
                      <strong>{{ coin.name }} | Compra | Venda</strong>
                    {% else %}
                      <strong>{{ coin.name }}</strong>
                    {% endif %}
                  </div>
                  <div>
                    {% if coin.name == "Dólar" %}
                      R$ {{ coin.value | format_coin }} | R$ {{ purchase.value }} | R$ {{ sale.value }}
                      <br><small></small>
                    {% else %}
                      R$ {{ coin.value | format_coin }}
                    {% endif %}
                  <div>
                </div>
              </div>
            </article>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}